name: Scope Testing

on: [push]

jobs:
  scope:
    runs-on: macOS-latest
    
    steps:
      - name: Check if SCOPE_DSN is set
        run: if [ "${{secrets.SCOPE_DSN}}" = "" ]; then exit 1; fi
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build dependencies
        run: carthage update --platform iOS
      - name: Scope for iOS
        uses: undefinedlabs/scope-for-swift-action@master
        with:
          dsn: ${{ secrets.SCOPE_DSN }}
          platform: ios
          codePath: true
        env:
          SCOPE_INSTRUMENTATION_HTTP_PAYLOADS: YES
